//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Kaynak kodu Microsoft.VSDesigner tarafından otomatik üretilmiş , Sürüm 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace E_commerce.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://tempuri.org/")]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DeleteSessionDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback AutocompleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddImageOperationCompleted;
        
        private System.Threading.SendOrPostCallback ShowImagesOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddCommentOperationCompleted;
        
        private System.Threading.SendOrPostCallback ShowCommentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectCommentOperationCompleted;
        
        private System.Threading.SendOrPostCallback CommentLikeOperationCompleted;
        
        private System.Threading.SendOrPostCallback CommentDislikeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCommentLikesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback RateProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckStockOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCategoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBrandOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMemoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback EditUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddProductFavoriteOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveProductFavoriteOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductFavoritesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetShoppingCartOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddShoppingCartOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveShoppingCartOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService1() {
            this.Url = global::E_commerce.Properties.Settings.Default.E_commerce_localhost_WebService1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DeleteSessionDataCompletedEventHandler DeleteSessionDataCompleted;
        
        /// <remarks/>
        public event AutocompleteCompletedEventHandler AutocompleteCompleted;
        
        /// <remarks/>
        public event AddImageCompletedEventHandler AddImageCompleted;
        
        /// <remarks/>
        public event ShowImagesCompletedEventHandler ShowImagesCompleted;
        
        /// <remarks/>
        public event AddCommentCompletedEventHandler AddCommentCompleted;
        
        /// <remarks/>
        public event ShowCommentsCompletedEventHandler ShowCommentsCompleted;
        
        /// <remarks/>
        public event SelectCommentCompletedEventHandler SelectCommentCompleted;
        
        /// <remarks/>
        public event CommentLikeCompletedEventHandler CommentLikeCompleted;
        
        /// <remarks/>
        public event CommentDislikeCompletedEventHandler CommentDislikeCompleted;
        
        /// <remarks/>
        public event GetCommentLikesCompletedEventHandler GetCommentLikesCompleted;
        
        /// <remarks/>
        public event GetProductIDCompletedEventHandler GetProductIDCompleted;
        
        /// <remarks/>
        public event UpdateProductCompletedEventHandler UpdateProductCompleted;
        
        /// <remarks/>
        public event RateProductCompletedEventHandler RateProductCompleted;
        
        /// <remarks/>
        public event CheckStockCompletedEventHandler CheckStockCompleted;
        
        /// <remarks/>
        public event AddProductCompletedEventHandler AddProductCompleted;
        
        /// <remarks/>
        public event DeleteProductCompletedEventHandler DeleteProductCompleted;
        
        /// <remarks/>
        public event GetCategoryCompletedEventHandler GetCategoryCompleted;
        
        /// <remarks/>
        public event GetBrandCompletedEventHandler GetBrandCompleted;
        
        /// <remarks/>
        public event GetMemoryCompletedEventHandler GetMemoryCompleted;
        
        /// <remarks/>
        public event EditUserCompletedEventHandler EditUserCompleted;
        
        /// <remarks/>
        public event AddProductFavoriteCompletedEventHandler AddProductFavoriteCompleted;
        
        /// <remarks/>
        public event RemoveProductFavoriteCompletedEventHandler RemoveProductFavoriteCompleted;
        
        /// <remarks/>
        public event GetProductFavoritesCompletedEventHandler GetProductFavoritesCompleted;
        
        /// <remarks/>
        public event GetShoppingCartCompletedEventHandler GetShoppingCartCompleted;
        
        /// <remarks/>
        public event AddShoppingCartCompletedEventHandler AddShoppingCartCompleted;
        
        /// <remarks/>
        public event RemoveShoppingCartCompletedEventHandler RemoveShoppingCartCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteSessionData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteSessionData() {
            this.Invoke("DeleteSessionData", new object[0]);
        }
        
        /// <remarks/>
        public void DeleteSessionDataAsync() {
            this.DeleteSessionDataAsync(null);
        }
        
        /// <remarks/>
        public void DeleteSessionDataAsync(object userState) {
            if ((this.DeleteSessionDataOperationCompleted == null)) {
                this.DeleteSessionDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteSessionDataOperationCompleted);
            }
            this.InvokeAsync("DeleteSessionData", new object[0], this.DeleteSessionDataOperationCompleted, userState);
        }
        
        private void OnDeleteSessionDataOperationCompleted(object arg) {
            if ((this.DeleteSessionDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteSessionDataCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Autocomplete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Autocomplete(string searchValue) {
            object[] results = this.Invoke("Autocomplete", new object[] {
                        searchValue});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AutocompleteAsync(string searchValue) {
            this.AutocompleteAsync(searchValue, null);
        }
        
        /// <remarks/>
        public void AutocompleteAsync(string searchValue, object userState) {
            if ((this.AutocompleteOperationCompleted == null)) {
                this.AutocompleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAutocompleteOperationCompleted);
            }
            this.InvokeAsync("Autocomplete", new object[] {
                        searchValue}, this.AutocompleteOperationCompleted, userState);
        }
        
        private void OnAutocompleteOperationCompleted(object arg) {
            if ((this.AutocompleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AutocompleteCompleted(this, new AutocompleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddImage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddImage(string values) {
            this.Invoke("AddImage", new object[] {
                        values});
        }
        
        /// <remarks/>
        public void AddImageAsync(string values) {
            this.AddImageAsync(values, null);
        }
        
        /// <remarks/>
        public void AddImageAsync(string values, object userState) {
            if ((this.AddImageOperationCompleted == null)) {
                this.AddImageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddImageOperationCompleted);
            }
            this.InvokeAsync("AddImage", new object[] {
                        values}, this.AddImageOperationCompleted, userState);
        }
        
        private void OnAddImageOperationCompleted(object arg) {
            if ((this.AddImageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddImageCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ShowImages", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ShowImages(int Product_id) {
            object[] results = this.Invoke("ShowImages", new object[] {
                        Product_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ShowImagesAsync(int Product_id) {
            this.ShowImagesAsync(Product_id, null);
        }
        
        /// <remarks/>
        public void ShowImagesAsync(int Product_id, object userState) {
            if ((this.ShowImagesOperationCompleted == null)) {
                this.ShowImagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnShowImagesOperationCompleted);
            }
            this.InvokeAsync("ShowImages", new object[] {
                        Product_id}, this.ShowImagesOperationCompleted, userState);
        }
        
        private void OnShowImagesOperationCompleted(object arg) {
            if ((this.ShowImagesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ShowImagesCompleted(this, new ShowImagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddComment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddComment(string comment) {
            object[] results = this.Invoke("AddComment", new object[] {
                        comment});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddCommentAsync(string comment) {
            this.AddCommentAsync(comment, null);
        }
        
        /// <remarks/>
        public void AddCommentAsync(string comment, object userState) {
            if ((this.AddCommentOperationCompleted == null)) {
                this.AddCommentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddCommentOperationCompleted);
            }
            this.InvokeAsync("AddComment", new object[] {
                        comment}, this.AddCommentOperationCompleted, userState);
        }
        
        private void OnAddCommentOperationCompleted(object arg) {
            if ((this.AddCommentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddCommentCompleted(this, new AddCommentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ShowComments", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ShowComments(int Product_id) {
            object[] results = this.Invoke("ShowComments", new object[] {
                        Product_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ShowCommentsAsync(int Product_id) {
            this.ShowCommentsAsync(Product_id, null);
        }
        
        /// <remarks/>
        public void ShowCommentsAsync(int Product_id, object userState) {
            if ((this.ShowCommentsOperationCompleted == null)) {
                this.ShowCommentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnShowCommentsOperationCompleted);
            }
            this.InvokeAsync("ShowComments", new object[] {
                        Product_id}, this.ShowCommentsOperationCompleted, userState);
        }
        
        private void OnShowCommentsOperationCompleted(object arg) {
            if ((this.ShowCommentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ShowCommentsCompleted(this, new ShowCommentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectComment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SelectComment(int Product_id) {
            object[] results = this.Invoke("SelectComment", new object[] {
                        Product_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SelectCommentAsync(int Product_id) {
            this.SelectCommentAsync(Product_id, null);
        }
        
        /// <remarks/>
        public void SelectCommentAsync(int Product_id, object userState) {
            if ((this.SelectCommentOperationCompleted == null)) {
                this.SelectCommentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectCommentOperationCompleted);
            }
            this.InvokeAsync("SelectComment", new object[] {
                        Product_id}, this.SelectCommentOperationCompleted, userState);
        }
        
        private void OnSelectCommentOperationCompleted(object arg) {
            if ((this.SelectCommentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectCommentCompleted(this, new SelectCommentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CommentLike", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CommentLike(string values) {
            object[] results = this.Invoke("CommentLike", new object[] {
                        values});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CommentLikeAsync(string values) {
            this.CommentLikeAsync(values, null);
        }
        
        /// <remarks/>
        public void CommentLikeAsync(string values, object userState) {
            if ((this.CommentLikeOperationCompleted == null)) {
                this.CommentLikeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCommentLikeOperationCompleted);
            }
            this.InvokeAsync("CommentLike", new object[] {
                        values}, this.CommentLikeOperationCompleted, userState);
        }
        
        private void OnCommentLikeOperationCompleted(object arg) {
            if ((this.CommentLikeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CommentLikeCompleted(this, new CommentLikeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CommentDislike", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CommentDislike(string values) {
            object[] results = this.Invoke("CommentDislike", new object[] {
                        values});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CommentDislikeAsync(string values) {
            this.CommentDislikeAsync(values, null);
        }
        
        /// <remarks/>
        public void CommentDislikeAsync(string values, object userState) {
            if ((this.CommentDislikeOperationCompleted == null)) {
                this.CommentDislikeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCommentDislikeOperationCompleted);
            }
            this.InvokeAsync("CommentDislike", new object[] {
                        values}, this.CommentDislikeOperationCompleted, userState);
        }
        
        private void OnCommentDislikeOperationCompleted(object arg) {
            if ((this.CommentDislikeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CommentDislikeCompleted(this, new CommentDislikeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCommentLikes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCommentLikes(int Comment_id) {
            object[] results = this.Invoke("GetCommentLikes", new object[] {
                        Comment_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCommentLikesAsync(int Comment_id) {
            this.GetCommentLikesAsync(Comment_id, null);
        }
        
        /// <remarks/>
        public void GetCommentLikesAsync(int Comment_id, object userState) {
            if ((this.GetCommentLikesOperationCompleted == null)) {
                this.GetCommentLikesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCommentLikesOperationCompleted);
            }
            this.InvokeAsync("GetCommentLikes", new object[] {
                        Comment_id}, this.GetCommentLikesOperationCompleted, userState);
        }
        
        private void OnGetCommentLikesOperationCompleted(object arg) {
            if ((this.GetCommentLikesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCommentLikesCompleted(this, new GetCommentLikesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProductID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetProductID(string values) {
            object[] results = this.Invoke("GetProductID", new object[] {
                        values});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductIDAsync(string values) {
            this.GetProductIDAsync(values, null);
        }
        
        /// <remarks/>
        public void GetProductIDAsync(string values, object userState) {
            if ((this.GetProductIDOperationCompleted == null)) {
                this.GetProductIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductIDOperationCompleted);
            }
            this.InvokeAsync("GetProductID", new object[] {
                        values}, this.GetProductIDOperationCompleted, userState);
        }
        
        private void OnGetProductIDOperationCompleted(object arg) {
            if ((this.GetProductIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductIDCompleted(this, new GetProductIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateProduct", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateProduct(string values) {
            object[] results = this.Invoke("UpdateProduct", new object[] {
                        values});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateProductAsync(string values) {
            this.UpdateProductAsync(values, null);
        }
        
        /// <remarks/>
        public void UpdateProductAsync(string values, object userState) {
            if ((this.UpdateProductOperationCompleted == null)) {
                this.UpdateProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateProductOperationCompleted);
            }
            this.InvokeAsync("UpdateProduct", new object[] {
                        values}, this.UpdateProductOperationCompleted, userState);
        }
        
        private void OnUpdateProductOperationCompleted(object arg) {
            if ((this.UpdateProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateProductCompleted(this, new UpdateProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RateProduct", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RateProduct(int rating) {
            object[] results = this.Invoke("RateProduct", new object[] {
                        rating});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RateProductAsync(int rating) {
            this.RateProductAsync(rating, null);
        }
        
        /// <remarks/>
        public void RateProductAsync(int rating, object userState) {
            if ((this.RateProductOperationCompleted == null)) {
                this.RateProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRateProductOperationCompleted);
            }
            this.InvokeAsync("RateProduct", new object[] {
                        rating}, this.RateProductOperationCompleted, userState);
        }
        
        private void OnRateProductOperationCompleted(object arg) {
            if ((this.RateProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RateProductCompleted(this, new RateProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckStock", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckStock(string productName) {
            object[] results = this.Invoke("CheckStock", new object[] {
                        productName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckStockAsync(string productName) {
            this.CheckStockAsync(productName, null);
        }
        
        /// <remarks/>
        public void CheckStockAsync(string productName, object userState) {
            if ((this.CheckStockOperationCompleted == null)) {
                this.CheckStockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckStockOperationCompleted);
            }
            this.InvokeAsync("CheckStock", new object[] {
                        productName}, this.CheckStockOperationCompleted, userState);
        }
        
        private void OnCheckStockOperationCompleted(object arg) {
            if ((this.CheckStockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckStockCompleted(this, new CheckStockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddProduct", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddProduct(string values) {
            object[] results = this.Invoke("AddProduct", new object[] {
                        values});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddProductAsync(string values) {
            this.AddProductAsync(values, null);
        }
        
        /// <remarks/>
        public void AddProductAsync(string values, object userState) {
            if ((this.AddProductOperationCompleted == null)) {
                this.AddProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddProductOperationCompleted);
            }
            this.InvokeAsync("AddProduct", new object[] {
                        values}, this.AddProductOperationCompleted, userState);
        }
        
        private void OnAddProductOperationCompleted(object arg) {
            if ((this.AddProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddProductCompleted(this, new AddProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteProduct", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DeleteProduct(int id) {
            object[] results = this.Invoke("DeleteProduct", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteProductAsync(int id) {
            this.DeleteProductAsync(id, null);
        }
        
        /// <remarks/>
        public void DeleteProductAsync(int id, object userState) {
            if ((this.DeleteProductOperationCompleted == null)) {
                this.DeleteProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteProductOperationCompleted);
            }
            this.InvokeAsync("DeleteProduct", new object[] {
                        id}, this.DeleteProductOperationCompleted, userState);
        }
        
        private void OnDeleteProductOperationCompleted(object arg) {
            if ((this.DeleteProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteProductCompleted(this, new DeleteProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCategory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCategory(int Category_id) {
            object[] results = this.Invoke("GetCategory", new object[] {
                        Category_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCategoryAsync(int Category_id) {
            this.GetCategoryAsync(Category_id, null);
        }
        
        /// <remarks/>
        public void GetCategoryAsync(int Category_id, object userState) {
            if ((this.GetCategoryOperationCompleted == null)) {
                this.GetCategoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCategoryOperationCompleted);
            }
            this.InvokeAsync("GetCategory", new object[] {
                        Category_id}, this.GetCategoryOperationCompleted, userState);
        }
        
        private void OnGetCategoryOperationCompleted(object arg) {
            if ((this.GetCategoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCategoryCompleted(this, new GetCategoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBrand", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetBrand(int Brand_id) {
            object[] results = this.Invoke("GetBrand", new object[] {
                        Brand_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetBrandAsync(int Brand_id) {
            this.GetBrandAsync(Brand_id, null);
        }
        
        /// <remarks/>
        public void GetBrandAsync(int Brand_id, object userState) {
            if ((this.GetBrandOperationCompleted == null)) {
                this.GetBrandOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBrandOperationCompleted);
            }
            this.InvokeAsync("GetBrand", new object[] {
                        Brand_id}, this.GetBrandOperationCompleted, userState);
        }
        
        private void OnGetBrandOperationCompleted(object arg) {
            if ((this.GetBrandCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBrandCompleted(this, new GetBrandCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMemory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetMemory(int Memory_id) {
            object[] results = this.Invoke("GetMemory", new object[] {
                        Memory_id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetMemoryAsync(int Memory_id) {
            this.GetMemoryAsync(Memory_id, null);
        }
        
        /// <remarks/>
        public void GetMemoryAsync(int Memory_id, object userState) {
            if ((this.GetMemoryOperationCompleted == null)) {
                this.GetMemoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMemoryOperationCompleted);
            }
            this.InvokeAsync("GetMemory", new object[] {
                        Memory_id}, this.GetMemoryOperationCompleted, userState);
        }
        
        private void OnGetMemoryOperationCompleted(object arg) {
            if ((this.GetMemoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMemoryCompleted(this, new GetMemoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EditUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EditUser(string values) {
            this.Invoke("EditUser", new object[] {
                        values});
        }
        
        /// <remarks/>
        public void EditUserAsync(string values) {
            this.EditUserAsync(values, null);
        }
        
        /// <remarks/>
        public void EditUserAsync(string values, object userState) {
            if ((this.EditUserOperationCompleted == null)) {
                this.EditUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditUserOperationCompleted);
            }
            this.InvokeAsync("EditUser", new object[] {
                        values}, this.EditUserOperationCompleted, userState);
        }
        
        private void OnEditUserOperationCompleted(object arg) {
            if ((this.EditUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditUserCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddProductFavorite", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddProductFavorite(string ProductName) {
            object[] results = this.Invoke("AddProductFavorite", new object[] {
                        ProductName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddProductFavoriteAsync(string ProductName) {
            this.AddProductFavoriteAsync(ProductName, null);
        }
        
        /// <remarks/>
        public void AddProductFavoriteAsync(string ProductName, object userState) {
            if ((this.AddProductFavoriteOperationCompleted == null)) {
                this.AddProductFavoriteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddProductFavoriteOperationCompleted);
            }
            this.InvokeAsync("AddProductFavorite", new object[] {
                        ProductName}, this.AddProductFavoriteOperationCompleted, userState);
        }
        
        private void OnAddProductFavoriteOperationCompleted(object arg) {
            if ((this.AddProductFavoriteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddProductFavoriteCompleted(this, new AddProductFavoriteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RemoveProductFavorite", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RemoveProductFavorite(string ProductName) {
            object[] results = this.Invoke("RemoveProductFavorite", new object[] {
                        ProductName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RemoveProductFavoriteAsync(string ProductName) {
            this.RemoveProductFavoriteAsync(ProductName, null);
        }
        
        /// <remarks/>
        public void RemoveProductFavoriteAsync(string ProductName, object userState) {
            if ((this.RemoveProductFavoriteOperationCompleted == null)) {
                this.RemoveProductFavoriteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveProductFavoriteOperationCompleted);
            }
            this.InvokeAsync("RemoveProductFavorite", new object[] {
                        ProductName}, this.RemoveProductFavoriteOperationCompleted, userState);
        }
        
        private void OnRemoveProductFavoriteOperationCompleted(object arg) {
            if ((this.RemoveProductFavoriteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveProductFavoriteCompleted(this, new RemoveProductFavoriteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProductFavorites", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetProductFavorites() {
            object[] results = this.Invoke("GetProductFavorites", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductFavoritesAsync() {
            this.GetProductFavoritesAsync(null);
        }
        
        /// <remarks/>
        public void GetProductFavoritesAsync(object userState) {
            if ((this.GetProductFavoritesOperationCompleted == null)) {
                this.GetProductFavoritesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductFavoritesOperationCompleted);
            }
            this.InvokeAsync("GetProductFavorites", new object[0], this.GetProductFavoritesOperationCompleted, userState);
        }
        
        private void OnGetProductFavoritesOperationCompleted(object arg) {
            if ((this.GetProductFavoritesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductFavoritesCompleted(this, new GetProductFavoritesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetShoppingCart", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetShoppingCart() {
            object[] results = this.Invoke("GetShoppingCart", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetShoppingCartAsync() {
            this.GetShoppingCartAsync(null);
        }
        
        /// <remarks/>
        public void GetShoppingCartAsync(object userState) {
            if ((this.GetShoppingCartOperationCompleted == null)) {
                this.GetShoppingCartOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetShoppingCartOperationCompleted);
            }
            this.InvokeAsync("GetShoppingCart", new object[0], this.GetShoppingCartOperationCompleted, userState);
        }
        
        private void OnGetShoppingCartOperationCompleted(object arg) {
            if ((this.GetShoppingCartCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetShoppingCartCompleted(this, new GetShoppingCartCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddShoppingCart", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddShoppingCart(int Product_id, int Quantity) {
            object[] results = this.Invoke("AddShoppingCart", new object[] {
                        Product_id,
                        Quantity});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddShoppingCartAsync(int Product_id, int Quantity) {
            this.AddShoppingCartAsync(Product_id, Quantity, null);
        }
        
        /// <remarks/>
        public void AddShoppingCartAsync(int Product_id, int Quantity, object userState) {
            if ((this.AddShoppingCartOperationCompleted == null)) {
                this.AddShoppingCartOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddShoppingCartOperationCompleted);
            }
            this.InvokeAsync("AddShoppingCart", new object[] {
                        Product_id,
                        Quantity}, this.AddShoppingCartOperationCompleted, userState);
        }
        
        private void OnAddShoppingCartOperationCompleted(object arg) {
            if ((this.AddShoppingCartCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddShoppingCartCompleted(this, new AddShoppingCartCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RemoveShoppingCart", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RemoveShoppingCart(string ProductName) {
            object[] results = this.Invoke("RemoveShoppingCart", new object[] {
                        ProductName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RemoveShoppingCartAsync(string ProductName) {
            this.RemoveShoppingCartAsync(ProductName, null);
        }
        
        /// <remarks/>
        public void RemoveShoppingCartAsync(string ProductName, object userState) {
            if ((this.RemoveShoppingCartOperationCompleted == null)) {
                this.RemoveShoppingCartOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveShoppingCartOperationCompleted);
            }
            this.InvokeAsync("RemoveShoppingCart", new object[] {
                        ProductName}, this.RemoveShoppingCartOperationCompleted, userState);
        }
        
        private void OnRemoveShoppingCartOperationCompleted(object arg) {
            if ((this.RemoveShoppingCartCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveShoppingCartCompleted(this, new RemoveShoppingCartCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DeleteSessionDataCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AutocompleteCompletedEventHandler(object sender, AutocompleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AutocompleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AutocompleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AddImageCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ShowImagesCompletedEventHandler(object sender, ShowImagesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ShowImagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ShowImagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AddCommentCompletedEventHandler(object sender, AddCommentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddCommentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddCommentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ShowCommentsCompletedEventHandler(object sender, ShowCommentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ShowCommentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ShowCommentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SelectCommentCompletedEventHandler(object sender, SelectCommentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectCommentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectCommentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CommentLikeCompletedEventHandler(object sender, CommentLikeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CommentLikeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CommentLikeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CommentDislikeCompletedEventHandler(object sender, CommentDislikeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CommentDislikeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CommentDislikeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetCommentLikesCompletedEventHandler(object sender, GetCommentLikesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCommentLikesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCommentLikesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetProductIDCompletedEventHandler(object sender, GetProductIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UpdateProductCompletedEventHandler(object sender, UpdateProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RateProductCompletedEventHandler(object sender, RateProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RateProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RateProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CheckStockCompletedEventHandler(object sender, CheckStockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckStockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckStockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AddProductCompletedEventHandler(object sender, AddProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DeleteProductCompletedEventHandler(object sender, DeleteProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetCategoryCompletedEventHandler(object sender, GetCategoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCategoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCategoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetBrandCompletedEventHandler(object sender, GetBrandCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBrandCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBrandCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetMemoryCompletedEventHandler(object sender, GetMemoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMemoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMemoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EditUserCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AddProductFavoriteCompletedEventHandler(object sender, AddProductFavoriteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddProductFavoriteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddProductFavoriteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RemoveProductFavoriteCompletedEventHandler(object sender, RemoveProductFavoriteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveProductFavoriteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveProductFavoriteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetProductFavoritesCompletedEventHandler(object sender, GetProductFavoritesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductFavoritesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductFavoritesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetShoppingCartCompletedEventHandler(object sender, GetShoppingCartCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetShoppingCartCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetShoppingCartCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AddShoppingCartCompletedEventHandler(object sender, AddShoppingCartCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddShoppingCartCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddShoppingCartCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RemoveShoppingCartCompletedEventHandler(object sender, RemoveShoppingCartCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveShoppingCartCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveShoppingCartCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591